"""The stress corpus: how people actually type, mapped to what the bot must return.

Shared by the pytest suite and the tuning harness. Every row is
`(typed_text, expected_kind, expected_id)`; `expected_id` of None means only the kind
(or status) is asserted. Kinds: personal | general | scenario | decline | glossary,
plus the pseudo-kinds `ambiguous` and `unmatched` for the honesty cases.

Add a row whenever a real phrasing fails — this file is the matcher's memory.
"""

# --- personal: the 18 canned questions, phrased every which way ----------------
PERSONAL = [
    ("Where should my next dollar go?", "personal", "next_dollar"),
    ("where should my next dollar go", "personal", "next_dollar"),
    ("what should i do first", "personal", "next_dollar"),
    ("where do i even start", "personal", "next_dollar"),
    ("whats my next move", "personal", "next_dollar"),
    ("im new to all this, what do i do", "personal", "next_dollar"),
    ("what should I prioritize right now", "personal", "next_dollar"),
    ("whats the first thing i should do with my money", "personal", "next_dollar"),
    ("ok so what comes first", "personal", "next_dollar"),
    ("why is the order what it is", "personal", "why_this_order"),
    ("why match before paying off debt", "personal", "why_this_order"),
    ("why is the emergency fund first", "personal", "why_this_order"),
    ("explain the waterfall", "personal", "why_this_order"),
    ("whats the logic behind this order", "personal", "why_this_order"),
    ("why hsa before ira?", "personal", "why_this_order"),
    ("do i have enough saved for emergencies", "personal", "emergency_fund"),
    ("is my emergency fund big enough", "personal", "emergency_fund"),
    ("do i have enough cash saved up", "personal", "emergency_fund"),
    ("how many months of expenses do i have", "personal", "emergency_fund"),
    ("am i covered if something goes wrong", "personal", "emergency_fund"),
    ("should i pay off debt or invest", "personal", "debt_or_invest"),
    ("pay off my debts or invest?", "personal", "debt_or_invest"),
    ("is my debt expensive enough to worry about", "personal", "debt_or_invest"),
    ("should i be investing while i have debt", "personal", "debt_or_invest"),
    ("which of my debts should i pay first", "personal", "debt_or_invest"),
    ("what do i actually do each month", "personal", "how_much_per_month"),
    ("whats my monthly plan", "personal", "how_much_per_month"),
    ("what do i do on payday", "personal", "how_much_per_month"),
    ("how much per paycheck should i be moving", "personal", "how_much_per_month"),
    ("give me the monthly breakdown", "personal", "how_much_per_month"),
    ("can i retire at the age i want", "personal", "can_i_retire_when_i_want"),
    ("am i on track to retire", "personal", "can_i_retire_when_i_want"),
    ("is my money gonna run out", "personal", "can_i_retire_when_i_want"),
    ("will i have enough to retire", "personal", "can_i_retire_when_i_want"),
    ("am i going to be ok", "personal", "can_i_retire_when_i_want"),
    ("will my money last", "personal", "can_i_retire_when_i_want"),
    ("how am i doing overall", "personal", "can_i_retire_when_i_want"),
    ("is my retirement plan on track?", "personal", "can_i_retire_when_i_want"),
    ("what changes if i retire earlier or later", "personal", "retirement_age_changes"),
    ("what happens if i retire early", "personal", "retirement_age_changes"),
    ("what ages matter for retirement", "personal", "retirement_age_changes"),
    ("what's different about retiring sooner", "personal", "retirement_age_changes"),
    ("how much do i need to invest to get there", "personal", "what_it_takes"),
    ("what would it take to hit my goal", "personal", "what_it_takes"),
    ("how much should i be putting away", "personal", "what_it_takes"),
    ("how much do i need to save to retire", "personal", "what_it_takes"),
    ("whats my coast number", "personal", "what_it_takes"),
    ("how much can i put in this year", "personal", "how_much_can_i_put_in"),
    ("how much can i put in my hsa", "personal", "how_much_can_i_put_in"),
    ("how much can I contribute to my 401k", "personal", "how_much_can_i_put_in"),
    ("what are my limits this year", "personal", "how_much_can_i_put_in"),
    ("how much room do i have in my ira", "personal", "how_much_can_i_put_in"),
    ("whats the max i can contribute", "personal", "how_much_can_i_put_in"),
    ("can i max out everything", "personal", "how_much_can_i_put_in"),
    ("can i contribute to a roth ira", "personal", "can_i_do_roth"),
    ("can i do a roth", "personal", "can_i_do_roth"),
    ("am i eligible for a roth ira", "personal", "can_i_do_roth"),
    ("do i make too much for a roth", "personal", "can_i_do_roth"),
    ("is my income too high for a roth ira", "personal", "can_i_do_roth"),
    ("do i qualify for a roth", "personal", "can_i_do_roth"),
    ("am i leaving employer match on the table", "personal", "am_i_missing_match"),
    ("free money from work", "personal", "am_i_missing_match"),
    ("am i getting my full match", "personal", "am_i_missing_match"),
    ("am i missing out on match", "personal", "am_i_missing_match"),
    ("is my 401k contribution enough to get the match", "personal", "am_i_missing_match"),
    ("am i leaving free money at work", "personal", "am_i_missing_match"),
    ("roth or traditional which should i pick", "personal", "roth_or_traditional"),
    ("roth or traditional for me", "personal", "roth_or_traditional"),
    ("should my 401k be roth", "personal", "roth_or_traditional"),
    ("should i switch to roth", "personal", "roth_or_traditional"),
    ("which is better for my situation, roth or traditional", "personal", "roth_or_traditional"),
    ("what about traditional", "personal", "roth_or_traditional"),
    ("what do i actually invest in", "personal", "what_to_invest_in"),
    ("what should i invest in", "personal", "what_to_invest_in"),
    ("what funds should i pick", "personal", "what_to_invest_in"),
    ("what do i buy in my ira", "personal", "what_to_invest_in"),
    ("is my money actually invested", "personal", "what_to_invest_in"),
    ("are my fees too high", "personal", "what_to_invest_in"),
    ("what should my 401k be invested in", "personal", "what_to_invest_in"),
    ("how is a taxable account taxed", "personal", "taxable_tax"),
    ("taxes on my brokerage account", "personal", "taxable_tax"),
    ("how is my brokerage taxed", "personal", "taxable_tax"),
    ("what is a 401k", "personal", "what_is_401k"),
    ("explain 401k to me", "personal", "what_is_401k"),
    ("how does a 401(k) work", "personal", "what_is_401k"),
    ("401k basics", "personal", "what_is_401k"),
    ("what's a 401k?", "personal", "what_is_401k"),
    ("what is an ira", "personal", "what_is_ira"),
    ("how does an ira work", "personal", "what_is_ira"),
    ("ira explained", "personal", "what_is_ira"),
    ("what is an hsa", "personal", "what_is_hsa"),
    ("hsa basics", "personal", "what_is_hsa"),
    ("what is a taxable brokerage account", "personal", "what_is_taxable"),
    ("what's a taxable account", "personal", "what_is_taxable"),
]

# --- general knowledge, including typos and slang ------------------------------
GENERAL = [
    ("how does compound interest work", "general", "compound_interest"),
    ("compunding", "general", "compound_interest"),
    ("why does everyone say start early", "general", "compound_interest"),
    ("interest on interest?", "general", "compound_interest"),
    ("what is the rule of 72", "general", "rule_of_72"),
    ("how long does it take money to double", "general", "rule_of_72"),
    ("what is an index fund", "general", "index_funds_explained"),
    ("why does everyone recommend index funds", "general", "index_funds_explained"),
    ("what is vti", "general", "ticker_symbols"),
    ("bogleheads three fund portfolio", "general", "index_funds_explained"),
    ("mutual fund vs etf", "general", "mutual_fund_vs_etf"),
    ("whats the difference between an etf and a mutual fund", "general", "mutual_fund_vs_etf"),
    ("should i buy etfs or mutual funds", "general", "mutual_fund_vs_etf"),
    ("what is an expense ratio", "general", "expense_ratios"),
    ("whats an expence ratio", "general", "expense_ratios"),
    ("why are fund fees bad", "general", "expense_ratios"),
    ("is a 1% fee a lot", "general", "expense_ratios"),
    ("how much do funds cost", "general", "expense_ratios"),
    ("what is a target date fund", "general", "target_date_funds"),
    ("is a 2060 fund enough on its own", "general", "target_date_funds"),
    ("what year target fund should i pick", "general", "target_date_funds"),
    ("what is diversification", "general", "diversification"),
    ("i own a lot of my company's stock is that bad", "general", "diversification"),
    ("how many stocks should i own", "general", "diversification"),
    ("what is asset allocation", "general", "asset_allocation"),
    ("what percentage should i have in stocks vs bonds", "general", "asset_allocation"),
    ("how aggressive should my portfolio be", "general", "asset_allocation"),
    ("stocks vs bonds", "general", "stocks_vs_bonds"),
    ("stocks and bonds", "general", "stocks_vs_bonds"),
    ("what is a bond", "general", "stocks_vs_bonds"),
    ("what are bonds", "general", "stocks_vs_bonds"),
    ("are bonds safe", "general", "stocks_vs_bonds"),
    ("what is dollar cost averaging", "general", "dollar_cost_averaging"),
    ("should i invest a lump sum all at once or over time", "general", "dollar_cost_averaging"),
    ("dca or lump sum", "general", "dollar_cost_averaging"),
    ("should i wait for the market to drop", "general", "market_timing"),
    ("is now a good time to invest", "general", "market_timing"),
    ("the market is at an all time high should i wait", "general", "market_timing"),
    ("should i buy the dip", "general", "market_timing"),
    ("market seems really expensive right now", "general", "market_timing"),
    ("what is rebalancing", "general", "rebalancing"),
    ("how often should i rebalance", "general", "rebalancing"),
    ("what are dividends", "general", "dividends"),
    ("are dividends free money", "general", "dividends"),
    ("should i reinvest dividends", "general", "dividends"),
    ("what is a brokerage", "general", "what_is_a_brokerage"),
    ("fidelity vs vanguard vs schwab", "general", "what_is_a_brokerage"),
    ("where do i open an ira", "general", "what_is_a_brokerage"),
    ("total market or s&p 500", "general", "total_market_vs_sp500"),
    ("vti vs voo", "general", "total_market_vs_sp500"),
    ("should i own international stocks", "general", "international_exposure"),
    ("what about vxus", "general", "international_exposure"),
    ("how do i know my risk tolerance", "general", "risk_tolerance"),
    ("im scared of losing money in the stock market", "general", "risk_tolerance"),
    ("is volatility the same as risk", "general", "volatility_vs_risk"),
    ("how risky are stocks really", "general", "volatility_vs_risk"),
    ("what is a bear market", "general", "bear_and_bull_markets"),
    ("what do i do in a crash", "general", "bear_and_bull_markets"),
    ("the market dropped should i sell", "general", "bear_and_bull_markets"),
    ("my portfolio is down 20% what do i do", "general", "bear_and_bull_markets"),
    ("what are fractional shares", "general", "fractional_shares"),
    ("i cant afford a whole share", "general", "fractional_shares"),
    ("what is a ticker symbol", "general", "ticker_symbols"),
    ("what does fxaix mean", "general", "ticker_symbols"),
    ("what happens at 59 1/2", "general", "age_59_half_explained"),
    ("early withdrawal penalty", "general", "age_59_half_explained"),
    ("can i take money out of my 401k early", "general", "age_59_half_explained"),
    ("what is the 10% penalty", "general", "age_59_half_explained"),
    ("how does the rule of 55 work", "general", "rule_of_55_explained"),
    ("what are rmds", "general", "rmds_explained"),
    ("required minimum distributions", "general", "rmds_explained"),
    ("do roth iras have rmds", "general", "rmds_explained"),
    ("what do i do with my old 401k", "general", "rollovers"),
    ("i left my job what happens to my 401k", "general", "rollovers"),
    ("should i roll over my 401k into an ira", "general", "rollovers"),
    ("how does vesting work", "general", "vesting_explained"),
    ("when is the match actually mine", "general", "vesting_explained"),
    ("how does social security work", "general", "social_security_basics"),
    ("when should i claim social security", "general", "social_security_basics"),
    ("will social security still exist", "general", "social_security_basics"),
    ("what is the 4% rule", "general", "safe_withdrawal_rate"),
    ("how much do i need to retire", "general", "safe_withdrawal_rate"),
    ("is a million dollars enough to retire", "general", "safe_withdrawal_rate"),
    ("whats my fire number", "general", "safe_withdrawal_rate"),
    ("what is sequence of returns risk", "general", "sequence_risk"),
    ("what if the market crashes right after i retire", "general", "sequence_risk"),
    ("what is a roth conversion", "general", "roth_conversions"),
    ("roth conversion ladder", "general", "roth_conversions"),
    ("how does a backdoor roth work", "general", "backdoor_roth_explained"),
    ("i make too much for a roth what do i do", "personal", "can_i_do_roth"),
    ("what is the pro rata rule", "general", "pro_rata_rule"),
    ("why is my backdoor roth taxable", "general", "pro_rata_rule"),
    ("what are catch up contributions", "general", "catch_up_contributions"),
    ("extra contribution room after 50", "general", "catch_up_contributions"),
    ("can i take money out of my roth early", "general", "roth_withdrawal_ordering"),
    ("can i withdraw roth contributions", "general", "roth_withdrawal_ordering"),
    ("how do people retire before 59 1/2", "general", "early_retirement_bridge"),
    ("how does fire work", "general", "early_retirement_bridge"),
    ("i want to retire in my 40s", "general", "early_retirement_bridge"),
    ("what about health insurance if i retire before 65", "general", "medicare_gap"),
    ("marginal vs effective tax rate", "general", "marginal_vs_effective"),
    ("will a raise push me into a higher bracket and cost me money", "general", "marginal_vs_effective"),
    ("how do tax brackets work", "general", "tax_brackets_explained"),
    ("do i pay the bracket rate on all my income", "general", "tax_brackets_explained"),
    ("what is the standard deduction", "general", "standard_deduction"),
    ("should i itemize", "general", "standard_deduction"),
    ("what does pre-tax mean", "general", "pretax_vs_posttax"),
    ("pretax vs after tax", "general", "pretax_vs_posttax"),
    ("roth vs traditional", "personal", "roth_or_traditional"),
    ("how do i decide between roth and traditional", "general", "roth_vs_traditional_mechanics"),
    ("what is tax loss harvesting", "general", "tax_loss_harvesting"),
    ("what is the wash sale rule", "general", "wash_sale_rule"),
    ("how are capital gains taxed", "general", "capital_gains_short_vs_long"),
    ("do i pay tax when i sell stocks", "general", "capital_gains_short_vs_long"),
    ("long term vs short term capital gains", "general", "capital_gains_short_vs_long"),
    ("what are qualified dividends", "general", "qualified_dividends"),
    ("what is tax drag", "general", "tax_drag"),
    ("where should i hold bonds, ira or taxable", "general", "tax_drag"),
    ("w2 vs 1099", "general", "w2_vs_1099"),
    ("im self employed what retirement account can i use", "general", "w2_vs_1099"),
    ("what is fica", "general", "fica_explained"),
    ("why is my paycheck so much smaller than my salary", "general", "fica_explained"),
    ("what does tax advantaged mean", "general", "tax_advantaged_vs_taxable"),
    ("why not just use a regular brokerage account", "general", "tax_advantaged_vs_taxable"),
    ("apr vs apy", "general", "apr_vs_apy"),
    ("whats the difference between apr and apy", "general", "apr_vs_apy"),
    ("what happens if i only pay the minimum on my credit card", "general", "minimum_payments"),
    ("how long to pay off a credit card paying the minimum", "general", "minimum_payments"),
    ("avalanche or snowball", "general", "avalanche_vs_snowball"),
    ("avalanche and snowball", "general", "avalanche_vs_snowball"),
    ("should i pay the smallest debt first or the highest interest", "general", "avalanche_vs_snowball"),
    ("what affects my credit score", "general", "credit_score_factors"),
    ("how do i improve my credit score", "general", "credit_score_factors"),
    ("does checking my credit score hurt it", "general", "credit_score_factors"),
    ("what is credit utilization", "general", "credit_utilization"),
    ("should i keep my card balance under 30%", "general", "credit_utilization"),
    ("is there such a thing as good debt", "general", "good_vs_bad_debt"),
    ("is a mortgage bad debt", "general", "good_vs_bad_debt"),
    ("when does paying off debt beat investing", "general", "when_debt_beats_investing"),
    ("pay extra on my mortgage or invest", "general", "when_debt_beats_investing"),
    ("how do student loans work", "general", "student_loans_basics"),
    ("federal vs private student loans", "general", "student_loans_basics"),
    ("what is pslf", "general", "student_loans_basics"),
    ("when does refinancing make sense", "general", "refinancing"),
    ("should i do a balance transfer", "general", "refinancing"),
    ("how big should my emergency fund be", "general", "emergency_fund_sizing"),
    ("3 months or 6 months of expenses", "general", "emergency_fund_sizing"),
    ("should i invest my emergency fund", "general", "emergency_fund_sizing"),
    ("what is a high yield savings account", "general", "high_yield_savings"),
    ("my bank pays nothing on savings", "general", "high_yield_savings"),
    ("what is a cd", "general", "cds_explained"),
    ("should i buy a cd", "general", "cds_explained"),
    ("what is a money market fund", "general", "money_market_funds"),
    ("what is spaxx", "general", "money_market_funds"),
    ("what does fdic insurance cover", "general", "fdic_insurance"),
    ("is my money safe if my bank fails", "general", "fdic_insurance"),
    ("why does inflation matter", "general", "inflation_explained"),
    ("is cash safe", "general", "inflation_explained"),
    ("what does real vs nominal mean", "general", "real_vs_nominal"),
    ("what is a sinking fund", "general", "sinking_funds"),
    ("saving for a car in 2 years where do i put it", "general", "sinking_funds"),
    ("gross vs net pay", "general", "gross_vs_net"),
    ("what is take home pay", "general", "gross_vs_net"),
    ("why do i get a tax refund", "general", "paycheck_withholding"),
    ("how does withholding work", "general", "paycheck_withholding"),
    ("what is the 50/30/20 rule", "general", "budgeting_50_30_20"),
    ("how do i make a budget", "general", "budgeting_50_30_20"),
    ("what savings rate do i need", "general", "savings_rate_explained"),
    ("is saving 10% enough", "general", "savings_rate_explained"),
    ("what percent of my income should i save", "general", "savings_rate_explained"),
    ("what is lifestyle creep", "general", "lifestyle_creep"),
    ("i got a raise but im not saving any more", "general", "lifestyle_creep"),
    ("what is net worth", "general", "net_worth"),
    ("how do i calculate my net worth", "general", "net_worth"),
    ("im paid biweekly does that change anything", "general", "pay_frequency"),
    ("three paycheck month", "general", "pay_frequency"),
    ("i got a raise what should i do with it", "general", "what_to_do_with_a_raise"),
    ("what should i do with side hustle money", "general", "side_income"),
    ("how does an employer match work", "general", "employer_match_deep"),
    ("50% up to 6% what does that mean", "general", "employer_match_deep"),
    ("what is a true up", "general", "employer_match_deep"),
    ("how do contribution limits work", "general", "contribution_limits_deep"),
    ("does the match count toward my limit", "general", "contribution_limits_deep"),
    ("can i max both a 401k and an ira in the same year", "general", "contribution_limits_deep"),
    ("what is a high deductible health plan", "general", "hdhp_explained"),
    ("ppo or hdhp", "general", "hdhp_explained"),
    ("what is a deductible", "general", "deductibles_explained"),
    ("deductible vs copay vs out of pocket max", "general", "deductibles_explained"),
    ("hsa vs fsa", "general", "hsa_vs_fsa"),
    ("what is an fsa", "general", "hsa_vs_fsa"),
    ("why is the hsa called a secret retirement account", "general", "hsa_as_retirement_account"),
    ("should i invest my hsa", "general", "hsa_as_retirement_account"),
    ("triple tax advantage", "general", "hsa_as_retirement_account"),
    ("term or whole life insurance", "general", "term_vs_whole_life"),
    ("is whole life a good investment", "general", "term_vs_whole_life"),
    ("do i need life insurance", "general", "term_vs_whole_life"),
    ("do i need disability insurance", "general", "disability_insurance_basics"),
    ("what insurance do i actually need", "general", "what_insurance_is_for"),
    ("are extended warranties worth it", "general", "what_insurance_is_for"),
    ("when should i open a taxable brokerage account", "general", "what_is_taxable_account"),
    ("ive maxed my 401k and ira, now what", "general", "what_is_taxable_account"),
]

# --- scenarios: a number in the question ---------------------------------------
SCENARIO = [
    ("How should I plan around my 35K of student debt?", "scenario", "debt_strategy"),
    ("how should i manage my 35k student debt with all of this", "scenario", "debt_strategy"),
    ("i have $35,000 in student loans at 6.5%, what do i do", "scenario", "debt_strategy"),
    ("i owe 8k on a credit card at 24%", "scenario", "debt_strategy"),
    ("thirty five thousand of student debt, help", "scenario", "debt_strategy"),
    ("my car loan is 12k at 7% should i pay it off early", "scenario", "debt_strategy"),
    ("should i throw money at my 20k student loans or invest", "scenario", "debt_strategy"),
    ("got 15k in credit card debt what should i do", "scenario", "debt_strategy"),
    ("should i pay off my credit card", "scenario", "debt_strategy"),
    ("how should i handle my credit card debt", "scenario", "debt_strategy"),
    ("i got 10k what do i do with it", "scenario", "windfall"),
    ("i got a $5,000 bonus, where should it go", "scenario", "windfall"),
    ("just inherited 50k", "scenario", "windfall"),
    ("what do i do with a 3000 dollar tax refund", "scenario", "windfall"),
    ("two grand bonus what now", "scenario", "windfall"),
    ("i came into $20,000", "scenario", "windfall"),
    ("what if i made 75k", "scenario", "income_change"),
    ("what if i earned 100k a year", "scenario", "income_change"),
    ("if my salary was 90,000", "scenario", "income_change"),
    ("what if i got a 10% raise", "scenario", "income_change"),
    ("what if i got a 5k raise", "scenario", "income_change"),
    ("new job paying 85k what changes", "scenario", "income_change"),
    ("what if i saved 300 a month", "scenario", "contribution_change"),
    ("what if i saved an extra 200 a month", "scenario", "contribution_change"),
    ("what if i put away $500 per paycheck", "scenario", "contribution_change"),
    ("if i invested 10k a year", "scenario", "contribution_change"),
    ("what if i contributed 1000 a month instead", "scenario", "contribution_change"),
    ("can i retire at 55", "scenario", "retirement_age"),
    ("what if i retire at 60", "scenario", "retirement_age"),
    ("what if i retired at 70 instead", "scenario", "retirement_age"),
    ("can i stop working at 50", "scenario", "retirement_age"),
    ("what does retiring at 62 look like", "scenario", "retirement_age"),
]

# --- needs_input: intent clear, number missing ----------------------------------
NEEDS_INPUT = [
    ("how should i handle my student debt", "needs_input", "debt_strategy"),
    ("what do i do about my car loan", "needs_input", "debt_strategy"),
]

# --- declines -------------------------------------------------------------------
DECLINE = [
    ("should i buy nvidia", "decline", "security_selection"),
    ("is tesla a good stock", "decline", "security_selection"),
    ("should i buy bitcoin", "decline", "security_selection"),
    ("whats the best stock to buy right now", "decline", "security_selection"),
    ("should i get into options trading", "decline", "security_selection"),
    ("will the market crash", "decline", "market_prediction"),
    ("is a recession coming", "decline", "market_prediction"),
    ("when will interest rates drop", "decline", "market_prediction"),
    ("how do i file my taxes", "decline", "tax_filing"),
    ("which tax form do i need", "decline", "tax_filing"),
    ("can i deduct my home office", "decline", "tax_filing"),
    ("do i need a will", "decline", "legal_estate"),
    ("should i file for bankruptcy", "decline", "legal_estate"),
    ("which life insurance company is best", "decline", "insurance_product"),
    ("should i buy an annuity", "decline", "insurance_product"),
    ("should i buy a house or keep renting", "decline", "personal_directive"),
    ("should i quit my job", "decline", "personal_directive"),
    ("what is the s&p at today", "decline", "live_data"),
    ("what are mortgage rates right now", "decline", "live_data"),
    ("how did the market do today", "decline", "live_data"),
    ("what funds are in my 401k", "decline", "plan_documents"),
    ("does my company do a true up", "decline", "plan_documents"),
]

# --- glossary fallback ----------------------------------------------------------
GLOSSARY = [
    ("what is magi", "glossary", "magi"),
    ("phase out", "glossary", "phase_out"),
    ("what does 72t mean", "glossary", "sepp_72t"),
    ("roth", "glossary", "roth"),
]

# --- honesty: these must NOT answer confidently ----------------------------------
AMBIGUOUS = [
    ("taxes", "ambiguous", None),
    ("interest", "ambiguous", None),
    ("fund", "ambiguous", None),
]
UNMATCHED = [
    ("asdfgh qwerty", "unmatched", None),
    ("purple monkey dishwasher", "unmatched", None),
    ("", "error", None),
]

# --- multi-part: two answers ----------------------------------------------------
MULTI = [
    ("roth or traditional and how much can i put in", ["roth_or_traditional", "how_much_can_i_put_in"]),
    ("what is an ira and what is a 401k", ["what_is_ira", "what_is_401k"]),
    ("what is an expense ratio and should i wait for a dip", ["expense_ratios", "market_timing"]),
]
# --- must NOT split ------------------------------------------------------------
NO_SPLIT = [
    "should i pay off debt and invest",
    "stocks and bonds",
    "avalanche and snowball",
    "roth and traditional",
    "hsa and fsa",
    "what is an hsa and how does it work",
]

# --- follow-up context ----------------------------------------------------------
FOLLOW_UPS = [
    # (first question, follow-up, expected id of the follow-up)
    ("can i contribute to a roth ira", "what about traditional", "roth_or_traditional"),
    ("what is an expense ratio", "and index funds", "index_funds_explained"),
    ("how much can i put in my hsa", "what about my ira", "how_much_can_i_put_in"),
]

# --- typo repair ----------------------------------------------------------------
TYPOS = [
    ("whats an expence ratio", "expense"),
    ("compunding", "compounding"),
    ("what are divdends", "dividends"),
    ("retirment age changes", "retirement"),
    ("emergancy fund", "emergency"),
]

ALL_ROUTED = PERSONAL + GENERAL + SCENARIO + GLOSSARY     # declines are asserted separately
